#!/bin/sh

if [ ${USER} = "root" ]
then
	vconftool set -t int memory/wifi/wifi_qs_exit 0 -g 6519 -i
	vconftool set -t int db/wifi/enable_quick_start 1 -g 6519 -i

	
	# Change file owner
	# 1. libraries
	# 2. executables
#	chown 5000:5000 /usr/bin/wifi-qs
	# 3. configurations
#	chown 5000:5000 /usr/share/edje/wifi-qs*
#	chown 5000:5000 /usr/share/locale/en_GB/LC_MESSAGES/wifi.mo
#        chown 5000:5000 /usr/share/locale/en_US/LC_MESSAGES/wifi.mo
#        chown 5000:5000 /usr/share/locale/ja/LC_MESSAGES/wifi.mo
#        chown 5000:5000 /usr/share/locale/ko/LC_MESSAGES/wifi.mo
#        chown 5000:5000 /usr/share/locale/zh_CN/LC_MESSAGES/wifi.mo
fi

# Change file permissions
# 1. libraries
# 2. executables
#chmod 700 /usr/bin/wifi-qs
# 3. configurations
#chmod 644 /usr/share/edje/wifi-qs*
#chmod 644 /usr/share/locale/en_GB/LC_MESSAGES/wifi.mo
#chmod 644 /usr/share/locale/en_US/LC_MESSAGES/wifi.mo
#chmod 644 /usr/share/locale/ja/LC_MESSAGES/wifi.mo
#chmod 644 /usr/share/locale/ko/LC_MESSAGES/wifi.mo
#chmod 644 /usr/share/locale/zh_CN/LC_MESSAGES/wifi.mo

